name: Badge Generators
on:
  workflow_dispatch:
  schedule:
    # 00:00 JST = 15:00 UTC
    - cron: "0 15 * * *"
    

permissions:
  contents: write

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=${{ github.repository_owner }}&margin-w=5&column=8'
          path: .github/assets/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          AUTO_PUSH: false

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: .github/assets/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&show_icons=true
          path: .github/assets/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
            mkdir -p .github/assets/profile-summary-card
            cp -r profile-summary-card-output/github/* .github/assets/profile-summary-card/
            git add .github/assets
            git commit -m "Update badges" || echo "No changes to commit"
            git push origin main
